title: yoonlog
email: ank04250425@gmail.com
description: "기록하고 정리하고 공유하는 개인 블로그"
baseurl: ""
url: "https://skyhanull.github.io"
lang: ko-KR
timezone: Asia/Seoul

author:
  name: yoon
  twitter:
  picture:

markdown: kramdown
theme:
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

gtm_id: ""
google_site_verification: ""
nav:
  - title: Home
    url: /
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/
  - title: About
    url: /about/

social:
  name: yoon
  links:
    - https://github.com/skyhanull

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
